### ISSUE TITLE
Setup flow is confusing

### ISSUE THREAD

**Issue by metcalfc** [docker/ecs-plugin#142]
Filling a ticket from an online conversation with Bret Fisher.

During `docker ecs setup` the user is prompted for a cluster name. It isn't clear to the user that the valid choices are:
- an existing ECS cluster name (or how that would be formatted arn,  short name, etc.
- blank

It seems odd to be prompted for a name and then immediately leave it blank. 

If you make a mistake and enter a name that isn't an existing cluster the context creates fine and then the error comes when you try to do something and the error is the "cluster doesn't exist" which makes me think I missed a step.

**Comment by BretFisher** [comment]
Thanks!

**Comment by ndeloof** [comment]
https://github.com/docker/ecs-plugin/pull/164 will probably help reduce misunderstanding with the setup flow

**Comment by ndeloof** [comment]
Need to be fully re-implemented considering support for `AWS_*` environment variables and SSO
