### ISSUE TITLE
feedback on launching in ecs

### ISSUE THREAD

**Issue by listaction** [docker/ecs-plugin#143]
amazing work - got it to work - saves me a lot of time . Here are somethings I noticed
1. it uses default vpc for some reason even if the cluster created is not on default vpc. I tried to have the cluster on a different vpc and it did not work.

2. If I have multiple aws credentials, and for some reason i pick a different one initially, it "remembers" the old credential id and keeps trying to use it and ecs secret management is not usable at this point. Had to clear out credentials.

3. I do not know what all roles are needed for the account that's needed to run this - had to use a highly privileged policy to get it to work. Would be good to list the policies needed by the runner for it to work. If it was documented , it was not clear.

4. Using the newly created context is somewhat a usability issue - not a big deal - but needs messaging IMO . 

👍

**Comment by ndeloof** [comment]
1. ECS integration indeed uses default AWS VPC by default. Would make sense we detect the cluster is using a distinct one and use this one as default. => https://github.com/docker/ecs-plugin/issues/149
Also see https://docs.docker.com/engine/context/ecs-integration/ and use of `x-aws-vpc` to select another VPC
2. We rely on aws CLI "profiles" to select the adequate credentials. If you can offer a reproduction scenario I can check if we miss something
3. documented here: https://github.com/docker/ecs-plugin/blob/master/docs/requirements.md#permissions, let me know if something was missing
4. This is beta 1 ¯\_(ツ)_/¯. Kidding apart, UX will significantly evolve in the incoming months, beta 1 is mostly a feature preview

**Comment by listaction** [comment]
a few more questions:
5. how can i set spot instances to be launched?
6. How can i set some of the instances to just have a private IP in a private subnet vs public subnet?

**Comment by ndeloof** [comment]
5. ECS integration only support Fargate Launch type for now, so you have no control on the ECS instances in use
6. the current design is to select the default subnets for Availability Zone in selected VPC (you can select a non-default VPC using `x-aws-vpc` extension). Not sure this would cover your need, feel free to open a dedicated issue explaining your use case.

**Comment by listaction** [comment]
thanks @ndeloof  - i was referring to this: https://aws.amazon.com/blogs/aws/aws-fargate-spot-now-generally-available/
I'll try 6 out and report back. BTW I was going off the demo and not your detailed docs - will give it a go with the docs!

**Comment by ndeloof** [comment]
ok I missed that. => https://github.com/docker/ecs-plugin/issues/151

**Comment by ndeloof** [comment]
I started investigating #151 but I can't find in AWS API how a Clutser is related to a VPC. 
@listaction can you please clarify where in the web console, coudformation stack or any other way you setup your Cluster, you selected a specific VPC to be used by the cluster ?
