### ISSUE TITLE
Support `docker stack` commands

### ISSUE THREAD

**Issue by smiller171** [docker/ecs-plugin#144]
IMO this should allow the use of `docker stack` commands so that we can make use of `deploy` instructions like replication.

**Comment by ndeloof** [comment]
Thanks for your feedback. The final UX is not defined yet and will definitively evolve. For now we map to docker-compose UX so adopted the `compose up` approach. 

About `deploy` section of a compose file, those are not tied to `docker stack` - sure, is has been introduced for this purpose - but 100% part of the [Compose specification](https://www.compose-spec.io/) and as such we obviously will support anything relevant that can be applied to Amazon ECS.

Lack of support for deploy.replicas was a mistake, see https://github.com/docker/ecs-plugin/pull/148

**Comment by smiller171** [comment]
https://docs.docker.com/compose/compose-file/#deploy

> Specify configuration related to the deployment and running of services. This only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up and docker-compose run.

It's in the spec, but only because docker-compose files can be used by `docker stack` commands. `docker-compose` commands ignore it.

**Comment by ndeloof** [comment]
> It's in the spec

Nope, the spec is http://compose-spec.io :)

You're right that the docs are way too specific to docker-compose vs stack, now that compose-spec has been created, we should fix the docs to avoid more confusion.
