### ISSUE TITLE
Support different target and published ports

### ISSUE THREAD

**Issue by smiller171** [docker/ecs-plugin#145]
I can't think of a reason this would be a hard technical limitation. ECS should support this

**Comment by ndeloof** [comment]
Fargate relying on awsvpc do not support network ports translation. This is a known limitation

**Comment by smiller171** [comment]
@ndeloof I stand corrected.

It lets me create the listener on a different port, but that doesn't actually direct traffic correctly. I don't understand why but that's not a problem for this project.

**Comment by ndeloof** [comment]
listeners _can_ indeed be used to expose a distinct port on load-balancer vs the actual service port, but this would only apply to externally consumed services, not for service-to-service connectivity, which would be terribly confusing. Next release of the ecs integration will reject a compose file which uses distinct published/target ports (and comparable incompatible settings in a compose file)
