### ISSUE TITLE
Support AWS::ECS::TaskDefinition ContainerDefinition Secrets

### ISSUE THREAD

**Issue by jpsikorra** [docker/ecs-plugin#152]
Support for this configuration option would be quite useful.

Implementation could be done via a docker-compose extension field. Then just pass the extension field to the `ecs.TaskDefinition_ContainerDefinition` `Secrets`.

**Comment by ndeloof** [comment]
we have plan to introduce support for secrets as https://github.com/docker/ecs-plugin/issues/13
