### ISSUE TITLE
LoadBalancer names cannot be longer than 32 characters

### ISSUE THREAD

**Issue by metcalfc** [docker/ecs-plugin#160]
Steps to repo:

1. put a compose file in a directory with a name longer than 20 characters.
2. `docker ecs compose up`

There is no step 3.

```Areallylongname123456789009876543211234567890LoadBalancer          ... CREATE_FAILED The load balancer name 'Areallylongname123456789009876543211234567890LoadBalancer' cannot be longer than '32' characters```

**Comment by ndeloof** [comment]
Nice catch.
I wonder we have comparable size limitations on other resources created.

**Comment by metcalfc** [comment]
I was thinking the same thing and took a long look in the docs. I could not for the life of me anywhere find the 32 character limit. 

But here is the list of types that allow custom names. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-name.html
