### ISSUE TITLE
Add support for more credential sources

### ISSUE THREAD

**Issue by chris-crone** [docker/ecs-plugin#166]
We currently only support credentials stored in `~/.aws/credentials` ([the "Shared Credentials File"](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html)). We should support other credential sources that the [SDK supports](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/).

[Feedback from ContainersFromTheCouch](https://www.twitch.tv/videos/678629831)

**Comment by ndeloof** [comment]
we indeed could rely on `credentials.NewEnvCredentials()` to import existing credentials and fall back to shared credentials file when we create those as part of the context setup.

**Comment by metcalfc** [comment]
I was talking to @kohidave about trying to align with how aws/copilot is doing creds so there is some consistency. They've got an issue we can meld minds and figure out something that works: https://github.com/aws/copilot-cli/issues/1181

**Comment by ndeloof** [comment]
We should align with the `aws` CLI and rely on `AWS_*` environment variables to get credentials from the adequate sources, to offer more flexibility to end users, without requirement for config/credentials files.

**Comment by ndeloof** [comment]
closing. credential support will be fully revisited as part of https://github.com/docker/compose-cli/issues/725
