### ISSUE TITLE
Don't set ECS cluster in context

### ISSUE THREAD

**Issue by ndeloof** [docker/ecs-plugin#169]
we allow use of existing AWS resources using `x-aws-*` extension fields, _but_ ECS cluster.
we also let user declare the ECS cluster to use within the `setup` command, which is pretty confusing (see #142)
I suggest we remove cluster from ecs context, and introduce `x-aws-cluster` for the same purpose. 
We also should offer more flexibility for users to get those set by external config files, or other ways.

proposed draft implementation: https://github.com/docker/ecs-plugin/pull/164

**Comment by CarmenAPuccio** [comment]
I think it would be safe to remove it from the setup and if a user didn't specify a `x-aws-cluster` in the compose file we just create a new cluster for them.
