### ISSUE TITLE
Existing Profiles Not Found

### ISSUE THREAD

**Issue by stevejgordon** [docker/ecs-plugin#174]
When running docker ecs setup it does not seem to read existing profiles from the .aws/credentials file. I'm using Windows 10.

I only get the option to select "new profile".

After completing the steps I was able to create a new profile successfully. Upon running the command again, that profile is not visible to select. Have I misunderstood how this should work?

**Comment by aiordache** [comment]
Thanks for reporting the issue. The profiles are being read from .aws/config only. I will add .aws/credentials as a fallback.

**Comment by stevejgordon** [comment]
Hi @aiordache.

Apologies, my original issue is bit unclear. For me, on Windows, profiles are not picked up from .aws/config.

```
[default]
output = json
region = eu-west-2

[demo]
output = json
region = eu-west-2
```

When running the command I only see the following:

```
E:\Projects\EcrWorkerDemo>docker ecs setup
Enter context name: aws
Enter context name: aws
Use the arrow keys to navigate: j k l h
? Select AWS Profile:
  > new profile
```

After running set up, choosing new profile and specifying the credentials, a profile is also not added to the config file. Only the credentials are added to the credentials file.

**Comment by stevejgordon** [comment]
I think I've identified the problem on my end after all. The named profile should include the profile prefix which for some reason is missing in my config file. After fixing that, the following does indeed work and is included in the list.

```
[profile demo]
output = json
region = eu-west-2
```

I think the only remaining query is should creating a new profile result it in being saved to the config file?

**Comment by aiordache** [comment]
@stevejgordon Yes, the profile should be saved to the config file. I will work on a fix for this bug. Thanks!

**Comment by nbihan-mediware** [comment]
I am not sure there is an actual fix, seems more a misconfiguration of the AWS CLI

See documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

the .aws/config file should look like
```
[default]
output = json
region = eu-west-2

[profile demo]
output = json
region = eu-west-2
```

the .aws/credentials
```
[default]
aws_access_key_id = [your default access key]
aws_secret_access_key = [your default secret]
[demo]
aws_access_key_id = [your access key]
aws_secret_access_key = [your secret]
```

**Comment by waydegg** [comment]
I've got the same problem on Ubuntu (Bionic 18.04).

**Comment by ndeloof** [comment]
closing. credential support will be fully revisited as part of https://github.com/docker/compose-cli/issues/725
