### ISSUE TITLE
Receiving a 'this tool requires the "new ARN resource ID format"' error on setup in Linux

### ISSUE THREAD

**Issue by mtyler68** [docker/ecs-plugin#175]
Running docker (19.03.12) on Linux (Ubuntu xenial) with ecs plugin (1.0.0-beta.2).

Following the steps for `docker ecs setup`:

```
Enter context name: aws
new profile
Enter profile name: awssandbox
Enter region: us-east-1
Enter credentials: y
Enter AWS Access Key ID: **********
Enter AWS Secret Access Key: ****************************************
this tool requires the "new ARN resource ID format"
```

`docker context ls` doesn't display the context I attempted to create and `docker context use awssandbox` reports context not found.

Also, I used `aws configure --profile pname` to create a profile for docker ecs to use. Docker ecs still failed to create the context.

**Comment by metcalfc** [comment]
You will need to log in to the AWS console and opt in to the new arn and resource format. You can read more here:

https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/

Or just go here:

https://console.aws.amazon.com/ecs/home?#/settings

**Comment by mtyler68** [comment]
Thank you! That worked when I logged in as the IAM user of the AWS access keys I was using.

**Comment by metcalfc** [comment]
Awesome. We'll get this into the docs as a requirement. //cc @usha-mandya

**Comment by usha-mandya** [comment]
@metcalfc PTAL - https://github.com/docker/docker.github.io/pull/11170

**Comment by metcalfc** [comment]
@usha-mandya Thanks. @mtyler68 thanks for the report. This is in the docs now!

**Comment by tperry-aadya** [comment]
I am actually continuing to experience this after updating the Account Settings on AWS and additionally matching the permissions listed in the documentation.

Is it possible there is some other missing piece that is required to get passed this error?

Currently on a Mac.
Verified that the user is attached to the correct policy.
Verified that the Account ID and Key are correct. AWS shows ECS is accessed.
Verified the permissions match the list here:
https://github.com/docker/ecs-plugin/blob/master/docs/requirements.md

**Comment by mtyler68** [comment]
@tperry-aadya : If you're getting the error that reads, `this tool requires the "new ARN resource ID format"`, then the user your using is not configured for the new ARN format.

Otherwise, what error are you getting?

**Comment by tperry-aadya** [comment]
> @tperry-aadya : If you're getting the error that reads, `this tool requires the "new ARN resource ID format"`, then the user your using is not configured for the new ARN format.
> 
> Otherwise, what error are you getting?

That is the error I am getting, however the user I am using is configured for the new ARN format. Or at least I think it is! I'll go back again and rebuild the user from scratch just in case.

**Comment by metcalfc** [comment]
I believe you will have to opt into the new format in every region individually. So also check if you opted into the specific region. I don't believe there is a way to opt in across the board.

**Comment by itmart** [comment]
I've done the steps described above but I can't use the context, does anyone know why this happens?

```
% docker context ls 
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
ecs                aws                                                                                                               
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm

% docker context use ecs  
context "ecs": not found
```

**Comment by benbowler** [comment]
Same here, I've "Enabled" each new ARN ID type on the selected region (eu-west-1) and I still get the error `his tool requires the "new ARN resource ID format"` on the `docker ecs setup` command.

**Comment by benbowler** [comment]
For me I created new root user credential in IAM and was able to connect, I'm not sure why I received this other error once I'd made the selection.
