### ISSUE TITLE
Stack creation time exceeded the specified timeout. Delete requested by user.

### ISSUE THREAD

**Issue by babarbaig1992** [docker/ecs-plugin#177]
Tried to deploy airflow example on ECS. Some of the resources created successfully and creation process took time while creating cluster. After sometime creation was cancelled and AWS Cloudformation displayed following error causing CoudFormation to rollback. 
"Stack creation time exceeded the specified timeout. Delete requested by user."

**Comment by chris-crone** [comment]
Hi @babarbaig1992!

Thanks for reporting the issue. Couple of questions:
1. Can you please link me to the example that you tried?
1. Do you know how long it took before it failed?

We currently have a [15 min timeout on deployment](https://github.com/docker/ecs-plugin/blob/6629d8e4cf4ca92423a044e85cf77ea873ecb0f8/pkg/amazon/sdk/sdk.go#L188) but if it takes longer to deploy things maybe we should make this configurable.

**Comment by babarbaig1992** [comment]
1. The code is just like this https://github.com/puckel/docker-airflow. Actually I can't share the actual code because it's owned by the organization I work in. Inside docker compose I'm creating multiple containers (webserver, flower, scheduler, worker) using the same airflow image.
2. Yes I think ECS cluster is taking more time. Cloudformation stack creation started at 12:36 and creation cancelled at 12:51 exactly after 15 minutes. So I believe this can be the issue.
Thanks for the response @chris-crone

**Comment by chris-crone** [comment]
Great, thanks @babarbaig1992!

I'll add this to our backlog and we'll look into our fix. Please don't hesitate to give us any other feedback you have on the tool!
