### ISSUE TITLE
AWS role is not picked up

### ISSUE THREAD

**Issue by andyrob00** [docker/ecs-plugin#181]
When running the **docker ecs setup** command and selecting an existing profile, the role assigned to that profile is not picked up so the context is not created.
Running command on Debian in WSL2

`andy@GB-LT-030992:~$ docker ecs setup
Enter context name: aws
✔ playpen

Enter region: eu-west-1

✗ Enter credentials:

AccessDeniedException: User: arn:aws:iam::************:user/andrew.robinson@***** is not authorized to perform: ecs:ListAccountSettings on resource: *`

**Comment by chris-crone** [comment]
Thanks for the report @andyrob00.

It looks like your AWS user does not have the permissions you need to deploy to ECS. You can find more details about what permissions you need here: https://github.com/docker/ecs-plugin/blob/master/docs/requirements.md

**Comment by andyrob00** [comment]
@chris-crone If I run the aws commands, with the role set, I am able to deploy to ECS. It, therefore, is the lack of using the aws role that is preventing the docker commands.
My user currently only has access to deploy with the defined role.

**Comment by ndeloof** [comment]
requirement for `ecs:ListAccountSettings` was added recently to check your account has the "new ARN and ID format" option set (as we need it to set Tags on services). Seems we need to update requirements.md

**Comment by ndeloof** [comment]
closing. credential support will be fully revisited as part of https://github.com/docker/compose-cli/issues/725
