### ISSUE TITLE
Tasks are not tagged while other resources are

### ISSUE THREAD

**Issue by chris-crone** [docker/ecs-plugin#188]
It appears we are tagging ECS clusters and services but not tasks:

* Cluster
  * Key - com.docker.compose.project
  * Value - dockerecsdemo
* Services
  * Key - com.docker.compose.service
  * Value – backend
  * Key - com.docker.compose.project
  * Value – dockerecsdemo
* Tasks – Null

It appears that co-pilot had a similar issue with propagating tags: https://github.com/aws/copilot-cli/issues/789.

**Comment by CarmenAPuccio** [comment]
@chris-crone I see this as Docker Labels on the Task and Tags still are empty?

❯ docker ecs version
Docker ECS plugin v1.0.0-beta.4 (1a949c6)

Docker Labels:
   * Key - com.docker.compose.service
   * Value - backend
   * Key - com.docker.compose.project
   * Value - dockerecsdemo

**Comment by chris-crone** [comment]
Arg, thanks for catching that @CarmenAPuccio. @ndeloof has put up #214 which should fix this.
