### ISSUE TITLE
Missing Instruction to Enable Experimental Features on Windows

### ISSUE THREAD

**Issue by Grunet** [docker/ecs-plugin#190]
After installing Docker Desktop Edge for Windows per the READme's instructions, I was finding that the "docker ecs version" command wasn't being recognized in a powershell terminal.

I eventually realized that I needed to toggle the 'Enable experimental features" option on in the Command Line tab of Docker Desktop's settings for it to work.

![image](https://user-images.githubusercontent.com/29322882/88460715-d17dfb00-ce63-11ea-816f-d1c4410db220.png)

After the fact I found documentation in [the Docker docs](https://docs.docker.com/engine/context/ecs-integration/#install-the-docker-ecs-integration-cli-on-linux) and in [this repo](https://github.com/docker/ecs-plugin/blob/master/docs/get-started-linux.md#plugin-install) about needing to do this for Linux, but I have yet to find an analogous mention for Windows.

**Comment by chris-crone** [comment]
Thanks for this feedback. I've forwarded it to the Desktop team.

Did you install Edge over an existing Stable release?

**Comment by Grunet** [comment]
Ah yes, I originally downloaded the Stable version ~1-2 weeks ago, sorry I should've mentioned that

**Comment by chris-crone** [comment]
Not a problem! That's a valid case that isn't covered in our documentation. I'll create a ticket to add this.

**Comment by chris-crone** [comment]
[Docs PR](https://github.com/docker/docker.github.io/pull/11188) is up so I'll close this.
