### ISSUE TITLE
Always Prompted to Create a New Profile when Creating AWS Context on Windows

### ISSUE THREAD

**Issue by Grunet** [docker/ecs-plugin#191]
Following the Docker docs's [instructions](https://docs.docker.com/engine/context/ecs-integration/) I ran the "docker ecs setup" command in a powershell terminal to create an AWS docker context. I was expecting to be able to use my default AWS profile's credentials that the aws-cli uses (stored at %UserProfile%/.aws/credentials) but instead I was prompted to create a new profile.

After doing so and trying it again I was also prompted to create a new profile, with no option as far as I could see to re-using the one I'd just made.

![image](https://user-images.githubusercontent.com/29322882/88460855-fa52c000-ce64-11ea-843e-7e9418ec5b4e.png)

OS: Windows 10 Pro, Version 1909
Docker Desktop: Version 2.3.3.2 (46784), Channel edge
Docker Command Line: v19.03.12
AWS CLI: 2.0.30 (Python/3.7.7 Windows/10 botocore/2.0.0dev34)

**Comment by chris-crone** [comment]
Hi @Grunet, thanks for the feedback!

It looks like you've run into this issue: https://github.com/docker/ecs-plugin/issues/174

We currently only read the `.aws/config` file to get profiles but will also read `.aws/credentials` in a future release.

**Comment by Grunet** [comment]
Ah yup, should've done a better job searching for a duplicate...closing this
