### ISSUE TITLE
Is using Docker Secrets with AWS possible?

### ISSUE THREAD

**Issue by Grunet** [docker/ecs-plugin#192]
I'm new to both Docker and AWS, and have been trying to get a local Node.js v14 script that gets info from an S3 bucket actually running in AWS itself. I've gotten as far as creating a local Docker container that pulls secrets it needs for a non-AWS API call from Docker Secrets (per [this recommendation](https://diogomonica.com/2017/03/27/why-you-shouldnt-use-env-variables-for-secret-data/) from the Docker getting started tutorial) but have been having trouble figuring out how to deploy it in AWS.

The ECS-CLI [doesn't appear to support minor versions of Docker Compose](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI.html) and Docker Secrets look to have been [added in 3.1 of Docker Compose](https://stackoverflow.com/questions/42139605/how-do-you-manage-secret-values-with-docker-compose-v3-1). And this new beta plugin appears to [only cover "services" compose attributes](https://github.com/docker/ecs-plugin/blob/d1b89ab76f3aa6b663475891d356ffeb90e72f22/pkg/amazon/backend/compatibility.go).

I'll be exploring alternatives to Docker Secrets that might integrate better with AWS, but would appreciate if anyone could confirm if this just isn't possible today, or if it actually is, could point me towards resources on making it work.

Thanks

**Comment by chris-crone** [comment]
Hi @Grunet,

Right now secrets on AWS are environment variable only. We currently only support using secrets for pulling private [Docker Hub images](https://docs.docker.com/engine/context/ecs-integration/#private-docker-images).

We are working to add file based secrets and should have them added to the Docker ECS integration soon.

**Comment by nebuk89** [comment]
Hey @Grunet thanks for this feedback, would you be interested in having a chat about how you found the experience generally and giving us some overall feedback? If so drop me an email on bengotch@docker.com
Thanks!

**Comment by Grunet** [comment]
Got it, thanks @chris-crone for all the recent support around this. I'll go ahead and give the Amazon SSM service a try for this

**Comment by ndeloof** [comment]
This will be covered by https://github.com/docker/ecs-plugin/issues/207
