### ISSUE TITLE
Plugins not fetching credentials from ~/.aws/credentials file?

### ISSUE THREAD

**Issue by akoumjian** [docker/ecs-plugin#198]
```bash
docker ecs setup
Enter context name: wordy█
Use the arrow keys to navigate: ↓ ↑ → ←
? Select AWS Profile:
  ▸ new profile
    contexter
    mulch

✔ contexter
✔ Enter region: █s-east-2

✗ Enter credentials:
```

I have the following entry on my aws config:

```
[profile contexter]
output=json
region=us-east-2
```

Which I had to set up to get it to recognize the entry. Then I have the following in my credentials file:

```
[contexter]
aws_access_key_id = *****
aws_secret_access_key = *****
```

The credentials are used just fine when I test them with the aws cli

```
aws sts --profile=contexter get-caller-identity

{
    "UserId": "***",
    "Account": "***",
    "Arn": "arn:aws:iam::***"
}
```

The user has all the permissions listed in the requirements. Is there a way to get more verbose output?
I feel like there's something obvious I'm missing here.

**Comment by kohidave** [comment]
Just for completeness, could you:

1. run `docker context ls` and ensure there's an AWS context?
2. run `docker inspect aws` and let us know what the output is?

Thanks so much !

**Comment by akoumjian** [comment]
Okay, it looks like it created the context. I think the `✗` in the last query made me think it wasn't working.

```
$ docker context ls
default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
wordy               aws
```

```
$ docker inspect aws
[]
Error: No such object: aws
```

Not sure what the last command was supposed to do.

**Comment by kohidave** [comment]
Ah I'm sorry, I meant to say inspect the aws context - so in your case `docker inspect wordy`.

**Comment by akoumjian** [comment]
No worries. Strangely it's actually the same:

```
~ docker inspect wordy
[]
Error: No such object: wordy
```

**Comment by ndeloof** [comment]
`docker context ls` shows your aws context was created, but you still use the default context so ecs plugin won't pick up credentials you configured.
You can either run `docker --context wordy ecs ...` or switch using `docker context use wordy`

**Comment by akoumjian** [comment]
Yeah, I know how to switch the context. I think it was simply the output of the setup command threw me off and made it seem like there was an error.
```
✗ Enter credentials:
```
There was no success message printed at the end and that was the last line out.

**Comment by ugurcemozturk** [comment]
I had the same issue. I tried to create my first context. When credentials have been asked, I've never seen my profiles, none of them, even I try many times.

I am running it on macOS with Docker ECS plugin v1.0.0-beta.4 (1a949c6).

Thanks!

**Comment by ndeloof** [comment]
closing. credential support will be fully revisited as part of https://github.com/docker/compose-cli/issues/725
