### ISSUE TITLE
unknown flag: --file

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [docker/ecs-plugin#201]
`docker ecs compose up --file docker-compose-deploy.yaml`

unknown flag: --file

**Comment by MaxmaxmaximusGitHub** [comment]
solution:

`docker ecs compose --file docker-compose-deploy.yaml up`

**Comment by ndeloof** [comment]
UX is still temporary and we don't plan to invest much during initial sprints, but for sure flags should be more flexible in use :)
