### ISSUE TITLE
Setting environment variables / interpolation works in convert but not up

### ISSUE THREAD

**Issue by ryanmalesic** [docker/ecs-plugin#202]
I used `docker ecs compose up` with a specified V1_API_VERSION=$V1_API_VERSION environment variable and the task had no definition of the variable. `docker ecs compose convert` on the other hand shows the environment variable in the configuration with correct name and value.

The same occurs with any type of string interpolation. I used `${}` syntax for the image url to be able to set it with a env var and it shows it in `convert`, but `up` fails because the image field is invalid (empty I suppose)

**Comment by ryanmalesic** [comment]
A diff of the two `convert` outputs (with env var and without) shows no difference between the two outputs

**Comment by ndeloof** [comment]
Fixed
