### ISSUE TITLE
Resource sg-XXXXXXX has a dependent object

### ISSUE THREAD

**Issue by jonathanisaac** [docker/ecs-plugin#203]
Hello guys, I found a problem when I use a pre-configured security group and I try to free the resources.

### Problem
When I try to free the resources, the error returns

`resource sg-XXXXXXX has a dependent object (Service: AmazonEC2; Status Code: 400; Error Code: DependencyViolation; Request ID: dd1afce1-deb5-45e0-9b46-b926bde41afb)
`
### Steps to Reproduce
At **docker-compose.yml**
`x-aws-securitygroup: "sg-XXXXXXX"
`

`docker ecs compose down 
`

### Proposed Solution
I propose to check the x-aws-securitygroup and if it is pre-configured, skip it on cleaning (same valid for vpc)

If it's my mistake, I'm sorry

**Comment by ndeloof** [comment]
when you set `x-aws-securitygroup` the resulting CloudFormation template should NOT create a security group, but use the one specified. You can confirm this by using `docker ecs compose convert` and check no SecurityGroup resource is defined, only references to specified sg-xxx
Based on this there's no reason CloudFormation would try to delete this security group. Can you please check CloudFormation events ?
