### ISSUE TITLE
Configure rolling update

### ISSUE THREAD

**Issue by ndeloof** [docker/ecs-plugin#206]
ECS support rolling deployments policies. As `compose up` updates an existing application using CloudFormation changeset, those will be applied. Service must be created with rolling policy and parameters set according to `deploy` section in compose file (optionaly relying on custom extensions when relevant)

**Comment by ndeloof** [comment]
Compose file format (based on Docker Swarm model) do support `deploy.updateConfig.parallelism`, as "_The number of containers to update at a time_".
AWS ECS uses a [distinct model](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html#cfn-ecs-service-deploymentconfiguration-maximumpercent) based on percent of healthy services during update: `MaximumPercent/MinimumHealthyPercent`

If `deploy.replicas` is set, we can compute those percents:
* MaximumPercent = (deploy.replicas + parallelism) / deploy.replicas
* MinimumHealthyPercent = (deploy.replicas - parallelism) / deploy.replicas

otherwise, we can warn user if `deploy.update_config.parallelism` has been set and let ECS apply defaults (200%/100%)

**Note:** this approach will probably be a problem once we introduce auto-scaling support; as replicas won't be relevant anymore.

We also can introduce support for `x-aws-maximun_percent` and `x-aws-minimun_percent` to give end-user full control on ECS rolling update policy.

**Comment by justincormack** [comment]
Hmm, I think that deploy.updateConfig.parallelism is not very generic, we should open a spec issue but I would be inclined to have x-aws specific controls as well, and then either change the spec to add a generic "rate" that can be used, or treat parallelism as being able to be an equivalent of rate and use that formula for aws but state in the spec that it isnt a precise mapping to paralllelism.
