### ISSUE TITLE
Allow user to set ECS task role

### ISSUE THREAD

**Issue by ndeloof** [docker/ecs-plugin#211]
ECS task is created with adequate IAM Managed policy so it can run and pull from ECR, but any user who relies on some AWS resource will need to pass additional roles/policies

We can rely on compose custom extensions to let user pass `x-aws-roles` and create the adequate IAM role for the task.

**Comment by kohidave** [comment]
Perhaps, in addition to this, we consider letting folks pass a policy in - that way the compose file can stay portable (this task needs S3 PUT permissions).
