### ISSUE TITLE
How to run two versions of the example application at the same time?

### ISSUE THREAD

**Issue by ledzeppelin** [docker/ecs-plugin#213]
Thanks for all your work on this great project.  I'm testing out `ecs-plugin` to do blue-green deployments by running two versions of the example application at the same time, and eventually updating the DNS to point to the later version's load balancer.

This works great:
```
docker ecs compose --project-name=example up
```
however when I run

```
docker ecs compose --project-name=improved_example up
```

I get the error:
```
FrontendTCP5000TargetGroup already exists in stack
```

What's the simplest approach I can pursue so I can run both versions of the application at the same time, with hopefully no changes to the compose file itself?

**Comment by ndeloof** [comment]
That's unfortunate, I should have noticed this as I use to run multiple time the same stack in parallel to run tests while another stack is shutting down.
We actually don't have to give TargetGroups a Name, better just drop this.

**Comment by ndeloof** [comment]
see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-name, we should just not set this attribute in CloudFormation stack
