### ISSUE TITLE
Problems to create the example in aws> FrontendService  (Never completes it creation so the stack is rolled back)

### ISSUE THREAD

**Issue by zelfick** [docker/ecs-plugin#217]
Has anyone had problems running the example application, from my side we i run the command:
docker ecs compose up
The process almost finish successful and all resources get created however, teh FrontendService nevers completes, so the stack is rollback:

FrontendServiceDiscoveryEntry ... CREATE_COMPLETE BackendServiceDiscoveryEntry  ... CREATE_COMPLETE 
BackendTaskDefinition         ... CREATE_COMPLETE FrontendTaskExecutionRole     ... CREATE_COMPLETE 
FrontendTCP5000TargetGroup    ... CREATE_COMPLETE BackendTaskExecutionRole      ... CREATE_COMPLETE 
CloudMap                      ... CREATE_COMPLETE FrontendTaskDefinition        ... CREATE_COMPLETE 
FrontendTCP5000Listener       ... CREATE_COMPLETE 
FrontendService               ... DELETE_IN_PROGRESS  (Never completes it creation so the stack is rolled back)
BackendService                ... CREATE_COMPLETE 
Cluster                       ... CREATE_COMPLETE 
ExampleDefaultNetwork         ... CREATE_COMPLETE 
example                       ... DELETE_IN_PROGRESS Stack creation time exceeded the specified timeout. Delete requested by user.

**Comment by ndeloof** [comment]
timeout has been removed so this error might change with more recent version, but still exists. 
Check on the ECS web console about the status of your service, especialy associated Tasks: check about STOPPED ones and reason for them to fail.

**Comment by desreid** [comment]
I'm having the same problem. In the Cloudformation UI the most recent event is FrontendService and it's stuck on Create-In-Progress status. It eventually times out and the stack self deletes. In the ECS UI there are two tasks, example-backend and example-frontend, both of which have active status. I'm using docker desktop edge 2.3.4.0 (46980) on OSX.

**Comment by ndeloof** [comment]
@desreid check the Tasks for those services, especially filtering by `STOPPED` state to check for provisioning errors.

**Comment by desreid** [comment]
Thanks for getting back to me. The two services are listed as 'ACTIVE'. The backend service has a single task that is listed as 'RUNNING'. The frontend service has a single task which is listed as 'PENDING' or 'PROVISIONING' but never running. Every two minutes or so it disappears, and then another event triggers to try to start it. Unfortunately there is no output in the Logs tab, so I can't tell exactly what is happening.

**Comment by ndeloof** [comment]
IIRC the `STOPPED` filter on tasks should show issue pulling images and such things. Not very obvious in the web UI, but should help diagnose this

**Comment by nadolny** [comment]
I have the same problem. I would like to inform you that when I get the image generated for the docker hub the problem does not occur. When I take the image generated for the ECR the problem occurs. Perhaps this will help to identify the problem.

**Comment by ndeloof** [comment]
@nadolny this suggest failure to pull image from registry (I can't remember how this appears on ECS web console to diagnose).
ECS Task is configured by Docker ECS integration to run with managed policy `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly` which grant pull access to ECR images **within the same AWS account**. Are you using a distinct configuration ?

**Comment by nadolny** [comment]
@ndeloof:

2 actions solved the problem:

a) % aws iam attach-user-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly  --user-name myUser

b)In docker-compose.yml
set field image to:
image: abcdefghijkl.dkr.ecr.us-east-1.amazonaws.com/XXXXXX/timestamper

And this time:

% docker ecs compose up                                                                                                   
WARN[0001] services.build: unsupported attribute        
ExampleDefaultNetwork         ... CREATE_COMPLETE 
ExampleLoadBalancer           ... CREATE_COMPLETE 
BackendTaskDefinition         ... CREATE_COMPLETE 
FrontendServiceDiscoveryEntry ... CREATE_COMPLETE 
FrontendTCP5000TargetGroup    ... CREATE_COMPLETE 
FrontendTCP5000Listener       ... CREATE_COMPLETE 
ExampleDefaultNetworkIngress  ... CREATE_COMPLETE 
CloudMap                      ... CREATE_COMPLETE 
BackendTaskExecutionRole      ... CREATE_COMPLETE 
BackendService                ... CREATE_COMPLETE 
FrontendTaskDefinition        ... CREATE_COMPLETE 
Cluster                       ... CREATE_COMPLETE 
LogGroup                      ... CREATE_COMPLETE 
BackendServiceDiscoveryEntry  ... CREATE_COMPLETE 
FrontendTaskExecutionRole     ... CREATE_COMPLETE 
FrontendService               ... CREATE_COMPLETE 
example                       ... CREATE_COMPLETE 


I worry about this warning:
WARN[0001] services.build: unsupported attribute


Thank you for your time

**Comment by zelfick** [comment]
Thanks all for your help i will try the solution proposed by @nadolny,  and any other suggestions from the comments and let you know how it goes.

**Comment by ndeloof** [comment]
> I worry about this warning:
> WARN[0001] services.build: unsupported attribute

ECS integration can't build images from compose file, image has to be built by another tool and published to a repository, so this warning.

**Comment by desreid** [comment]
> IIRC the `STOPPED` filter on tasks should show issue pulling images and such things. Not very obvious in the web UI, but should help diagnose this

Thanks @ndeloof. The STOPPED filter showed the failed tasks if I got there before the stack collapsed. That helped diagnose the problem, it was just a simple auth issue when pulling from docker.

**Comment by camilosantana** [comment]
to elaborate and possibly help others, specific instructions are available [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/stopped-task-errors.html) for this scenario

in my case, it took forever for the docker to propagate and become available on docker hub.

**Comment by ndeloof** [comment]
we need to improve ECS integration so we check service state and detect `CannotPullContainerError`

**Comment by ndeloof** [comment]
to be addressed by https://github.com/docker/compose-cli/issues/596
