### ISSUE TITLE
Use SSM parameters directly as an environment variable

### ISSUE THREAD

**Issue by chathsuom** [docker/ecs-plugin#239]
Is it possible to use SSM parameters directly as environment variables without sidecar container?

**Comment by ndeloof** [comment]
There's no technical reason preventing to support this, but this would prevent the same service codebase to run both for local development with Compose secrets support and when deploying on ECS.

**Comment by chathsuom** [comment]
Just wondering if it can be available both to environment and to the file.

**Comment by ndeloof** [comment]
closing: As docker-compose does not support exposing secrets as environment variables, doing so would break the portability of compose application model between local development and production deployment on ECS.
