### ISSUE TITLE
Docker ECS Example App is not connecting to backend

### ISSUE THREAD

**Issue by balasridhar** [docker/ecs-plugin#243]
Hello, 

Tried deploying the example app to my aws account. Deployed fine, but getting the error that the frontend app is not able to find `backend:6379` when trying to access the url on port 5000. Works without issues locally though. 

Any help is appreciated. Noticed that the LOCALDOMAIN variable injected looks like this:

LOCALDOMAIN | us-west-2.compute.internal example.local

error from the app:

`  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to backend:6379. Name does not resolve.

`
docker compose file attached 
[sample-docker-compose.txt](https://github.com/docker/ecs-plugin/files/5127614/sample-docker-compose.txt)

**Comment by ndeloof** [comment]
There's a delay for CloudMap DNS resolution to be ready on application start, even with the support of `depends_on`. This is something we are investigating with AWS.

As a workaround, application code should handle connection retry, or you can add a wait script as entrypoint to postpone application boot until the `backend` DNS name can be resolved.

**Comment by balasridhar** [comment]
@ndeloof Thanks for the explanation. Will try the wait approach for now.

**Comment by balasridhar** [comment]
@ndeloof tried the wait approach, how long do you think we need to wait, still no dice. 

logs from the frontend application.

frontend    | Timeout! After 300 seconds some hosts are still not reachable
frontend    | --------------------------------------------------------
frontend    |  docker-compose-wait 2.7.2
frontend    | ---------------------------
frontend    | Starting with configuration:
frontend    |  - Hosts to be waiting for: [backend:6379]
frontend    |  - Timeout before failure: 300 seconds 
frontend    |  - TCP connection timeout before retry: 30 seconds 
frontend    |  - Sleeping time before checking for hosts availability: 0 seconds
frontend    |  - Sleeping time once all hosts are available: 0 seconds
frontend    |  - Sleeping time between retries: 30 seconds
frontend    | --------------------------------------------------------
frontend    | Checking availability of backend:6379
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Host backend:6379 not yet available...
frontend    | Timeout! After 300 seconds some hosts are still not reachable
frontend    | --------------------------------------------------------

**Comment by balasridhar** [comment]
@ndeloof figured it out, the VPC we were using doesnt have DNS resolution/DNS hostnames was not enabled. So once we enabled that, it started working.

I will close the issue. thanks for the help.

**Comment by ndeloof** [comment]
As we check vpc exists we could also check it has this required DNS resolution enabled. Do you know the option name for this?

**Comment by metcalfc** [comment]
```
{
  "Type" : "AWS::EC2::VPC",
  "Properties" : {
      "CidrBlock" : String,
      "EnableDnsHostnames" : Boolean,
      "EnableDnsSupport" : Boolean,
      "InstanceTenancy" : String,
      "Tags" : [ Tag, ... ]
    }
}
```

**Comment by kohidave** [comment]
Yea, `EnableDnsSupport` is what we want to check! 

We can use [DescribeVPCAttribute](https://godoc.org/github.com/datacratic/aws-sdk-go/service/ec2#EC2.DescribeVPCAttribute) and pass in `enableDnsSupport` as the attribute.

**Comment by balasridhar** [comment]
Sorry, for not responding earlier. as @kohidave  suggested i enabled `EnableDnsSupport` and `EnableDNSHostnames` as well.
