### ISSUE TITLE
Why does using port 80 create two A records for the load balancer?

### ISSUE THREAD

**Issue by ledzeppelin** [docker/ecs-plugin#244]
I noticed this issue occurring in my application so to reproduce I ran the example app by changing
```
ports:
  - "5000:5000"
```
to
```
ports:
  - "80:80"
```
I ran the example app using port 80 instead of 5000.  When I query dns, the answer section shows two IP addresses.
```
dig ExampleLoadBalancer-123.us-east-2.elb.amazonaws.com

...

;; ANSWER SECTION:
ExampleLoadBalancer-123.us-east-2.elb.amazonaws.com. 30 IN A 3.13.165.123
ExampleLoadBalancer-123.us-east-2.elb.amazonaws.com. 30 IN A 3.12.248.124
```

**Comment by ledzeppelin** [comment]
Actually... I'm noticing this issue still occurring in my own application even after changing port 80 to 8080.  This is a huge problem because the 2nd A record doesn't work - making a request on that IP just hangs.

Any clue why this may be occurring?

**Comment by ndeloof** [comment]
For services with port 80 or 443 ECS integration do provision an Application Load Balancer, otherwise we create a Network Load Balancer. Multiple DNS records just demonstrate Load Balancer replication.
Does this create any specific usability issue ?

**Comment by ledzeppelin** [comment]
Ah... that makes sense.

> Does this create any specific usability issue ?

If I'm using port 80, making the request to the first ip works but the second ip address causes the request to hang.  However when using a port like 5000 and there's a single A record, everything works fine.

By the way thanks for the improvements from v1.0.0-beta.4 to v1.0.0-beta.5.  The Progress Writer is **REALLY** awesome - I love the real time feedback.

**Comment by ledzeppelin** [comment]
Hi @ndeloof - I'm running my web services on ports 8080 and 8008, however when I query the loadbalancer's dns via dig there are two A records.

I started to observe that half of my web requests were failing and was able to confirm that whenever there are two A records, **one of them doesn't work** (ie requests made to one of the ips just hangs.)  The thing that makes this very difficult to troubleshoot is that for the load balancer, sometimes there's only one A record, other times there is two, and I'm not sure what the criteria is for the 2nd one being created.

Is there any way to ensure only a single A record gets created for the load balancer, or that the if two A records are created that they will both be able to route traffic?

Additional Details (not sure if this is helpful, just wanted to be comprehensive)
- I'm using a non-default project name `docker ecs compose --project-name=myapp2 up`
- After the containers are created/started, in Route53 I create a record where I set **Value/Route traffic to** to **Alias to Network Load Balancer** and select the dualstack load balancer.

**Comment by ledzeppelin** [comment]
Just wanted to note that every time I run `compose up`, the load balancer runs in us-east-2a, us-east-2c and that the connectivity issue always seems to be with the public ip in the us-east-2c.  Since I created my aws account I haven't changed the default VPC or subnets in us-east-2, or any ec2 regions.

**Comment by ndeloof** [comment]
closing.
We don't manage how AWS ELB do generate DNS records. 
If you can confirm creating a LoadBalancer for ECS without ECS integration results in a distinct setup, then we could try to understand how those differ from the one produced by `docker compose up`
