### ISSUE TITLE
No method to update ECS application via the command

### ISSUE THREAD

**Issue by benbowler** [docker/ecs-plugin#246]
Good afternoon, the plugin is fantastic for setting up a service, there's not a clear workflow for updating an existing app as far as I can see.

When I have an existing deployed app and I run `docker ecs compose up` I get the error : `failed waiting for successful resource state`

So the only way I can deploy a new version of the app right now is to `compose down` then `compose up` and update my dns endpoints. 

Have I missed something.

**Comment by ndeloof** [comment]
`compose up` is the right way to update an application.
Is there any additional error message reported ?
Can you please check on AWS web console > CloudFormation the status of your deployed application ?

**Comment by jonathanisaac** [comment]
I'm experiencing the same problem

```
docker compose up
WARN[0000] services.build: unsupported attribute        
ResourceNotReady: failed waiting for successful resource state
```

CloudFormation Status: CREATE_COMPLETE

No additional messages.

**Comment by ndeloof** [comment]
Here again, please check AWS web console and CloudFormation stack status, events, and reported errors.
Something went wrong, but the API doesn't give much details

**Comment by jonathanisaac** [comment]
I ended up rebuilding the project to check.
This time I noticed an entry in Change Sets (CloudFormation):

```
Status: FAILED
Status reason: **The submitted information didn't contain changes. Submit different information to create a change set.**
Execution status: UNAVAILABLE
```

I changed the source code of the "app" and generated a new image (and published it on the ECR) before applying a docker compose up. Apparently CloudFormation is returning a "no-changes condition", I believe it is necessary to handle the event.

**Comment by ndeloof** [comment]
@jonathanisaac for ECS to detect a change the image reference need to be updated. If you use the same tag (maybe `latest`?) and rebuild/push image the task definition is still unchanged. A common practice is to reference images by sha256, I wonder if we could transparently manage this as the compose app is converted to CloudFormation (like docker/app does), wdyt @chris-crone ?

**Comment by chris-crone** [comment]
> I wonder if we could transparently manage this as the compose app is converted to CloudFormation (like docker/app does), wdyt @chris-crone ?

If it is a safe assumption that the client has access to ECR (i.e.: it's exposed publicly and the client is authenticated with at least pull access) then I think this is a good idea. Given that this is common in the development cycle (build, push, run), we need to think about how we can make this flow better.

**Comment by jonathanisaac** [comment]
@ndeloof I understood, and in the end, versioning the image makes sense in this case. As @chris-crone  mentioned, it would be interesting if the development cycle (build, push, run) was automated and flowed a little better (my opinion). Maybe the `docker compose up` would take care of the build/push(versioning)/run
