### ISSUE TITLE
Compose file changes is overwriting the services inside ECS

### ISSUE THREAD

**Issue by rbngtm1** [docker/ecs-plugin#250]
Hi,
I am having issue when deploying applications using compose file.

For example. 
1. First compose file
```
version: "3.4"
services:
   service_A
```

if I try "docker ecs compose up" it brings up the cluster with name of directory that I am working on, forex here I have 'test' where service_A is running.

If I try to add more changes through another compose file. (I am using "x-aws-cluster: test", since I want service_B service to append on the "**test** cluster".)

2. Second compose file
```
version: "3.4"
x-aws-cluster: test
services:
   service_B
```

With this change, I am seeing service A is getting deleted and service B is provisioning. 

Now the question is, How can we get service_B provisioned without deleting service A.

OPTIONS TRIED: Tried service A and service B in one compose file, got ERROR stating that cloudformation doesn't support more than 51200 bytes. 

Any help is appreciated

**Comment by ajlozier** [comment]
I have three services in my `docker-compose.yml` file but don't have an issue deploying them all at once. I am wondering why you might be hitting the 51k limit?

I do see AWS allows you to bypass this limit if you push the template to an s3 bucket and then deploy against that. Maybe this could be an enhancement?

Perhaps you could export the cloudformation template, upload it manually and deploy using cloudformation, supplying the necessary parameters. Not ideal but might be a workaround for the time being. 

Hope this helps

**Comment by rbngtm1** [comment]
Thank you @ajlozier.

I have more services running in each file. I gave above example for simplifying my question. I tried uploading cloudformation template to S3 and deploy using cloudformation. Since, it required more parameters to pass in which was not convenient as deploying docker-compose.yml file. So, was wondering if there was other way around.

**Comment by ajlozier** [comment]
It seems like an option to push/deploy via s3 would be a good enhancement that would resolve your issue
