### ISSUE TITLE
Documentation on website for ECS Plugin install actually links to ACI Plugin install script

### ISSUE THREAD

**Issue by GavinRay97** [docker/ecs-plugin#255]
https://docs.docker.com/engine/context/ecs-integration/#install-script

![image](https://user-images.githubusercontent.com/26604994/92315373-f8773300-efb2-11ea-8c65-7fa8074df15d.png)

**Comment by ndeloof** [comment]
github repository name is not accurate here: despite the name, ECS support if fully integrated into https://github.com/docker/aci-integration-beta/releases/tag/v0.1.14

This is a temporary distribution repository, once we get https://github.com/docker/aci-integration-beta/issues/1 done we will update the documentation with canonical links
