### ISSUE TITLE
Why not use AWS CDK?

### ISSUE THREAD

**Issue by mrpackethead** [docker/ecs-plugin#256]
This is an intresting project, but a LOT of what is happening, ( in terms of creating CF templates ) is already well covered by aws-cdk..   A well created cdk construct woudl cover this off so well, and would mean that it woudl be very easy to implment / modify everything else aws?

**Comment by curveddesign** [comment]
If I am correct the AWS CDK does not use the new cloud agnostic [docker compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md) .  The new spec does not just work with AWS but also Azure and Google Cloud too. We need something simple and elegant that just works without needing to toil with Cloud Formation!

**Comment by mrpackethead** [comment]
Thats correct curved... you can't natively hand AWS docker compose. However you can most definately process it with CDK and have it create the CF for you.   Its simple and elegent.

This may be which end of the stick you are coming from.. If your coming from a docker end, wanting to use AWS, this may appear easiler.  If you are coming from AWS side and wanting to use a docker-compose in your project, then using cdk may well be easier.

**Comment by ndeloof** [comment]
CDK has been considered so far mostly as an inspiration to use comparable solutions.
As "The CDK is available in the following languages: JavaScript, TypeScript, Python, Java, .NET" it's not relevant for being used with the Docker CLI which is a Golang project

**Comment by mrpackethead** [comment]
I understand where your coming from..   This projects inspired me to do the flip direction.   I coded a pretty decent chunk of it up today,.. I'm taking the docker-compose file in its native format, and processing it with python/aws-cdk to produce my cf.  Theres so many variations in environmetns that being able to do it this way works for me.   

It all comes down to what you consider your 'primary' tools to be. For me. Its not docker.. but for those who it is, i fully get why you'd want it integrated intot he CLI
