### ISSUE TITLE
AWS Temporary Credentials

### ISSUE THREAD

**Issue by GibbMatt** [docker/ecs-plugin#257]
Please would it be possible to provide an additional parameter to creating ecs context  (docker context create ecs myecscontext) to include AWS Security Token, required in case of use of temporary credentials (and in prompts for the same). The current flags available are --key-id and -secret-key. Temporary credentials require additional security token to be sent, when communicating to AWS, also created in credentials file on creation from AWS. Thank-you Matthew.

**Comment by camilosantana** [comment]
is this something you can script and place in a `Makefile` target?

pull your temp key_id and key, set it in your environment and continue from there.

**Comment by ndeloof** [comment]
For non-basic scenarios better for you to create an aws profile with `aws` CLI and use this one for your docker context. The `key+secret` support is here only for people with basic needs and no aws tooling installed.

**Comment by GibbMatt** [comment]
Thank-you for your reply, I'll  look at aws CLI, not sure how to assign/use  aws profile for docker context, but good to know you can do this.  I guess maybe set the docker context to the aws profile as a context.

**Comment by ndeloof** [comment]
closing. credential support will be fully revisited as part of https://github.com/docker/compose-cli/issues/725
