### ISSUE TITLE
IAM Policy of user  is not updated dynamically

### ISSUE THREAD

**Issue by diranetafen** [docker/ecs-plugin#264]
Hi
I've an issue when i update the policy of my user.
In fact, went I add a new policy, the ecs plugin continues to tell me that I've not enough right to create some resources.
So I need to run docker ECS setup again to log in again.
Can you update the right automatically before running the resource creation?

regards

**Comment by ndeloof** [comment]
`docker ecs setup`  just check your `~/.aws/config` file to select a profile _or_ create one with credentials you enter manualy.
As you update your AWS user those credentials should not require to be updated.

Please check wit the `aws` command line that you get the same behaviour

**Comment by diranetafen** [comment]
I don't use aws cli, i'm using secret and secret key during docker ecs setup
So went i uodate my user policy, i need to run again docker ecs setup to enable docker ecs to  be able to make the action

**Comment by ndeloof** [comment]
Sounds weird to me updating account permission force you to regenerate keys.
As ECS integration doesn't manage getting those keys from your AWS account (there's no API for this purpose) we can't update them

**Comment by diranetafen** [comment]
No
update permission is not forcing to regenerate key.
So my problem is that I need to run docker ecs setup to enter the same info (same credentials) and them the resources is created correctly

**Comment by ndeloof** [comment]
Can you pleas echeck youre `$HOME/.aws/credential` file?

I expect it only contains:
```
[profile_name]
aws_access_key_id = ************
aws_secret_access_key = ************
```

This should be the same data you enter by `docker ecs setup`, and we don't store much on disk, so re-running this command with same key+secret should not change this file. I can't see any reason running it _again_ changes the other `ecs ..` commands to make your deployment successful :'(

**Comment by diranetafen** [comment]
ok fine, i also don't why i need to re-run ecs setup
So i close the issue
but if you can me a test on your side i will appreciate it.
Thanks again for your time
