### ISSUE TITLE
Calling variable

### ISSUE THREAD

**Issue by rbngtm1** [docker/ecs-plugin#266]
Hello everyone,
I am trying to call variable form docker compose file that is used to spin up ecs cluster.

I tried specifying --env-file=filename option (where I get unknown flag: --env-file) as well as keeping variables in .env file. But it's not working.

The same option works with docker-compose up for building locally.

**Comment by ndeloof** [comment]
Docker ECS integration indeed doesn't strictly replicate docker-compose behaviour and does not support .env files, this is something we have to manage.

**Comment by rbngtm1** [comment]
Thanks @ndeloof
