### ISSUE TITLE
Compare existing task definition with service definition

### ISSUE THREAD

**Issue by ndeloof** [docker/ecs-plugin#9]
This will allow to only update services that require a new TaskDefinition version

**Comment by jonathanisaac** [comment]
I look forward to this change.
Is it one of those "must-have", any feedback for a pre-beta 2 version?

Even so, congratulations on the excellent work.

**Comment by ndeloof** [comment]
As we rely on CloudFormation and this one do manage updates by ChangeSets, I'll close this obsolete issue
